language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/soldat/ci/master/build-package.sh | sh'

branches:
  only:
    - master
